src_dir: src
public_dir: docs

title: sinchang's personal front page

bookmarks:
  - name: 微博
    url: https://m.weibo.cn/beta
    favicon: weibo.ico
  - name: Twitter
    url: https://tweetdeck.twitter.com
    favicon: twitter.ico
  - name: V2EX
    url: https://v2ex.com/
    favicon: v2ex.png
  - name: GitHub
    url: https://github.com/sinchang
    favicon: github.ico
  - name: YouTube
    url: https://youtube.com
    favicon: youtube.png

  - category: 技术资讯
  - name: Hacker News
    url: https://news.ycombinator.com/
    favicon: hacker-news.ico
  - name: Echo JS
    url: http://www.echojs.com/
    favicon: echo-js.ico
  - name: 掘金
    url: https://juejin.im/
    favicon: juejin.ico
  - name: 开发者头条
    url: https://toutiao.io/
    favicon: toutiao.ico
  - name: GitHub Trending
    url: https://github.com/trending
    favicon: github.ico
  - name: Product Hunt
    url: https://www.producthunt.com/
    favicon: product-hunt.ico
  - name: reddit
    url: https://www.reddit.com/
    favicon: reddit.ico

  - category: 技术社区
  - name: CNode
    url: https://cnodejs.org/
    favicon: cnode.png
  - name: SegmentFault
    url: https://segmentfault.com/
    favicon: segmentfault.ico
  - name: Laravel China
    url: https://laravel-china.org/
    favicon: laravel.png
  - name: Ruby China
    url: https://ruby-china.org/
    favicon: ruby-china.png

  - category: 社交网络
  - name: 知乎
    url: https://www.zhihu.com/
    favicon: zhihu.ico
  - name: 豆瓣
    url: https://www.douban.com/
    favicon: douban.ico
